name: Deploy kubernetes cluster to Amazon EKS
on:
  push:
    branches:
      - main
jobs:
  deploy-to-aws-eks:
    runs-on: macos-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@v3

      - name: install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          ./aws/install -i /usr/local/aws-cli -b /usr/local/bin

      - name: print cli version
        run: aws --version